### ISSUE TITLE
Model checkpoint of vgg19 seems to be a checkpoint of vgg16

### ISSUE THREAD

**Issue by Charan0** [vinthony/depth-distillation#3]
Hey! I wanted to use the VGG best backbone and found the link for it in the readme which took me to google drive. After downloading and going through the checkpoint and the keys it looks like it is actually vgg16 but it is mentioned as vgg19. Can you please confirm and rename the link in the readme?
Thanks in advance

**Comment by vinthony** [comment]
Thanks to point it out! README has been fixed to vgg16.
